name = "starter-webapp-frontend"
compatibility_date = "2024-06-15"
main = "src/worker.js"

# Assets configuration for static files
[assets]
directory = "dist"
binding = "ASSETS"


# Environment variables
[vars]
VITE_API_URL = "https://starter-webapp-backend.onrender.com"
VITE_ENVIRONMENT = "production"

# Development environment
[env.development]
name = "starter-webapp-frontend-dev"

[env.development.vars]
VITE_API_URL = "http://localhost:8000"
VITE_ENVIRONMENT = "development"

# Production environment
[env.production]
name = "starter-webapp-frontend"

[env.production.vars]
VITE_API_URL = "https://starter-webapp-backend.onrender.com"
VITE_ENVIRONMENT = "production"

# Preview environment
[env.preview]
name = "starter-webapp-frontend-preview"

[env.preview.vars]
VITE_API_URL = "https://starter-webapp-backend.onrender.com"
VITE_ENVIRONMENT = "preview"