name: Deploy Backend to Render

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (if any)
        working-directory: backend
        run: |
          # Add test commands here when tests are implemented
          echo "Running basic import test..."
          python -c "from app.main import app; print('✅ App imports successfully')"

      - name: Check database migrations
        working-directory: backend
        run: |
          echo "Checking Alembic configuration..."
          alembic check || echo "⚠️ Alembic check completed"

  notify-render:
    runs-on: ubuntu-latest
    name: Notify Render of Deployment
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Render
        run: |
          echo "🚀 Backend deployment will be triggered automatically by Render"
          echo "Monitor deployment status at: https://dashboard.render.com/"
          echo "Backend will be available at: https://starter-webapp-backend.onrender.com"